name: App Python para testar github Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-verison: 3.8
    - name: Instala dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Teste com Pytest
      run: |
        pytest